name: Mirror to shamze-pages

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    if: github.repository == 'yossiDisk/Shamze'
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: yossiDisk/shamze-pages
      DOMAIN: shamze.com
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Mirror to target repo (with debug)
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euo pipefail
          set -x
          if [ -z "${TOKEN:-}" ]; then
            echo "❌ MIRROR_TOKEN is empty!" >&2
            exit 1
          else
            echo "✅ MIRROR_TOKEN present"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote remove target || true
          git remote add target https://$TOKEN@github.com/${TARGET_REPO}.git
          git remote get-url target | sed -e 's#//.*@#//<token>@#' -e 's#\.git#<…>.git#'
          echo -n "Trying git ls-remote… "
          git ls-remote target HEAD && echo "✅ ls-remote OK" || { echo "❌ ls-remote FAILED"; exit 1; }

          # המירור בפועל
          git push --force target main:main

      - name: Ensure CNAME exists in target repo
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -euo pipefail
          set -x
          tmpdir="$(mktemp -d)"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # שיבוט מהיר של היעד
          git clone --depth 1 https://$TOKEN@github.com/${TARGET_REPO}.git "$tmpdir"
          cd "$tmpdir"

          # צור/עדכן CNAME רק אם התוכן שונה
          if [ ! -f CNAME ] || ! cmp -s <(printf '%s\n' "$DOMAIN") CNAME; then
            printf '%s\n' "$DOMAIN" > CNAME
            git add CNAME
            git commit -m "chore: ensure CNAME ($DOMAIN) after mirror"
            git push origin HEAD:main
            echo "✅ CNAME ensured in target repo"
          else
            echo "ℹ️ CNAME already up-to-date"
          fi
